spring:
  application:
      name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: umrodrigues-user
      password: Rodrigues1996

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false